### ISSUE TITLE
Update the TWIST to 1.4

### ISSUE THREAD

**Issue by luizvilla** [owntech-foundation/TWIST#2]
**Description**

While discussing with a colleague on the heatsink of the twist, I've realized he had the kicad for the 1.3 instead of the 1.4. 

**Solution**

Push the latest version of the 1.4 into the github. It is already available on the gitlab.

**Comment by pierre-haessig** [comment]
I believe the 1.4 branch is [now available](https://github.com/owntech-foundation/TWIST/tree/TWIST-V1.4.X/KiCAD_files) so that this issue can be closed.

**Comment by jalinei** [comment]
Thanks @pierre-haessig for pointing it out, I'm closing.
